// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVq2PMSNPz7OfmFg2BNzTbPZmENhxbz0',
    appId: '1:196471462485:web:17a8acd5e6cdf1e0e112dc',
    messagingSenderId: '196471462485',
    projectId: 'course-correct-e31f4',
    authDomain: 'course-correct-e31f4.firebaseapp.com',
    storageBucket: 'course-correct-e31f4.firebasestorage.app',
    measurementId: 'G-Y63K1R9WZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-i3DWX6RknINGEfpocDPKJm5vrcoVLE',
    appId: '1:196471462485:android:32f284ca7fd82e02e112dc',
    messagingSenderId: '196471462485',
    projectId: 'course-correct-e31f4',
    storageBucket: 'course-correct-e31f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxMBayQNbVdqSOYbtczPgLnkl5YYQ0Fk',
    appId: '1:196471462485:ios:d7b7081570a795dfe112dc',
    messagingSenderId: '196471462485',
    projectId: 'course-correct-e31f4',
    storageBucket: 'course-correct-e31f4.firebasestorage.app',
    iosBundleId: 'com.example.courseCorrect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxMBayQNbVdqSOYbtczPgLnkl5YYQ0Fk',
    appId: '1:196471462485:ios:d7b7081570a795dfe112dc',
    messagingSenderId: '196471462485',
    projectId: 'course-correct-e31f4',
    storageBucket: 'course-correct-e31f4.firebasestorage.app',
    iosBundleId: 'com.example.courseCorrect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzVq2PMSNPz7OfmFg2BNzTbPZmENhxbz0',
    appId: '1:196471462485:web:5e6b83569fb71a3de112dc',
    messagingSenderId: '196471462485',
    projectId: 'course-correct-e31f4',
    authDomain: 'course-correct-e31f4.firebaseapp.com',
    storageBucket: 'course-correct-e31f4.firebasestorage.app',
    measurementId: 'G-04BBQB232T',
  );
}
